// Generated by https://quicktype.io

export interface MedicinasAPIPaginatedResponse {
    drugGroup: DrugGroup;
}

export interface DrugGroup {
    name:         null;
    conceptGroup: ConceptGroup[];
}

export interface ConceptGroup {
    tty:                string;
    conceptProperties?: ConceptProperty[];
}

export interface ConceptProperty {
    rxcui:    string;
    name:     string;
    synonym:  string;
    tty:      TTY;
    language: Language;
    suppress: Suppress;
    umlscui:  string;
}

export enum Language {
    Eng = "ENG",
}

export enum Suppress {
    N = "N",
}

export enum TTY {
    Sbd = "SBD",
    Scd = "SCD",
}
